### ISSUE TITLE
Generating pkl & painting_info.txt files

### ISSUE THREAD

**Issue by c-tanner** [robgon-art/MachineRay#2]
Hello,

First off, thank you very much for contributing a fantastic project to the open source community and providing a [great writeup](https://towardsdatascience.com/machineray-using-ai-to-create-abstract-art-39829438076a) on it's implementation.

One key component missing is generating the `pkl` and `painting_info.txt` files that are ingested by the Google Colab workflow. Any guidance on this is appreciated!

**Comment by robgon-art** [comment]
Hi c-tanner,

I will look into this issue...

**Comment by robgon-art** [comment]
I added [get_painting_info.py](https://github.com/robgon-art/MachineRay/blob/master/get_painting_info.py) to create the painting_info.txt file.

To get the .pkl file, you have to create the dataset and train StyleGAN2.

Here are the commands I used in a Colab.

```
!python stylegan2/dataset_tool.py create_from_images 'datasets/paintings' 'art/resized/'

!python stylegan2/run_training.py --config=config-e --metrics=none \
   --data-dir='/content/datasets' --dataset=paintings \
   --mirror-augment=true \
   --total-kimg=5000 \
   --result-dir='/content/drive/MyDrive/results_nv_1024'
```

**Comment by c-tanner** [comment]
Thanks for the quick response! I'll give this a shot.

**Comment by c-tanner** [comment]
Hi @robgon-art,

Thanks again for the help in getting the dataset files generated. As I wait for the initial training run to complete, I'm curious as to:

1.  How subsequent runs of the Google Colab workflow (after the 24 hours of runtime are consumed) are chained together;
2.  How this relates to the final `.pkl` file that is ingested into the [example workflow](https://colab.research.google.com/drive/1ug46zEa4-oKNQnp7oCv0JsZWvCV96lhN?usp=sharing); and therefore
3. How `network-snapshot-000188.pkl` in the example workflow is obtained. 

Each time the workflow you provided is run, I noticed sequentially numbered folders being created inside of Google Drive within the `results_nv_1024` folder (screenshot attached). Inside of each of those folders is a `.pkl` file (`network-snapshot-000000.pkl`). Are these numerous `.pkl` files collated at the end of the 13-15 days that you took to run the training, or is a single file from the latest run used?

I noticed you mentioned in your article:

> I also used Google Drive to retain the work in progress between runs.

So I am assuming the `.pkl` files are preserved between runs and are collated at the end somehow?

I also noticed:

> It took about 13 days to train the GAN, sending 5 million source images through the system.

Is this 5 million from the same 850 source images generated in the initial steps? Or 5 million unique source images?

Just wondering if I have this set up correctly. Thanks in advance, any guidance here is appreciated.

<img width="1110" alt="Screen Shot 2021-03-07 at 7 50 44 PM" src="https://user-images.githubusercontent.com/55005098/110261504-80e48980-7f7e-11eb-867d-6c4b5403d5bf.png">

<img width="1117" alt="Screen Shot 2021-03-07 at 7 51 00 PM" src="https://user-images.githubusercontent.com/55005098/110261502-804bf300-7f7e-11eb-91ca-c0a65a097d07.png">

**Comment by robgon-art** [comment]
Yes, when you check the output in the Colab, you should see the system picking up from where it last left off. Like this:

`Loading networks from "/content/drive/My Drive/results_nv_1024_week5/00025-stylegan2-paintings-1gpu-config-e/network-snapshot-004984.pkl"...`

Also, you should notice the improved quality of the "fake" images being saved.

I only used 850 source images, with * 7 for the augmentation (and another * 2 for flipping horizontally). So there were 11,900 different variations of images that the GAN saw.

The five million number in the article is from the total number of source images passed through the system. I trained the model for over 5,000 iterations of 1 kimg each, which stands for one thousand images.

Also, you should check out the newer StyleGAN2 ADA which does automatic augmentation and trains a lot faster. You can check it out in my article, here: https://towardsdatascience.com/creating-abstract-art-with-stylegan2-ada-ea3676396ffb

Cheers,

- Rob
