### ISSUE TITLE
Can I sell generated image?

### ISSUE THREAD

**Issue by ghost** [robgon-art/MachineRay#4]
Hi Sir.
Thank you very much for share this fantastic project.
Can I include generated image with my project and sell them?

Thank you.

**Comment by robgon-art** [comment]
Hi Khalidoz,

Unfortunately, Nvidia has released their StyleGAN 2 under a non-commercial license:
https://github.com/NVlabs/stylegan2/blob/master/LICENSE.txt
  
And because MachineRay is based on StyleGAN 2, I released it under a non-commercial license:
https://github.com/robgon-art/MachineRay/blob/master/License.txt

So it can’t be used to to make money.

**Comment by ghost** [comment]
Sorry, I have another question "What is the probability of duplicating an image produced by the code?".

**Thank you very much.**

**Comment by robgon-art** [comment]
Hi Khalidoz,

This is a good question!

On one hand, the top number image combinations for any system generating a 1,024x1,024 full color image is: w * h * r * g *b = 1024 * 1024 * 256 * 256 * 256 = 1.76E+13. A big number.

On the other hand, if you generated 10 billion images from system A, then generated another 10 billion images from system B, that makes 1E+14 comparisons, which makes it likely that there would be at least one duplicate, and even more likely to have substantially similar images.

Further, if both systems use the same GAN model and both were trained on the same dataset, then it becomes even more likely to have substantially similar images.

**Comment by ghost** [comment]
I got it, Thank you.

**Comment by stereomatchingkiss** [comment]
> 
> 
> Hi Khalidoz,
> 
> Unfortunately, Nvidia has released their StyleGAN 2 under a non-commercial license:
> https://github.com/NVlabs/stylegan2/blob/master/LICENSE.txt
> 
> And because MachineRay is based on StyleGAN 2, I released it under a non-commercial license:
> https://github.com/robgon-art/MachineRay/blob/master/License.txt
> 
> So it can’t be used to to make money.

There exist MIT implementation of stylegan2-ADA

**Comment by robgon-art** [comment]
Yes, I collected together two open-source projects that, when combined, is a working StyleGAN2 ADA implementation released under the MIT License. You can see it here: [https://github.com/robgon-art/stylegan2-ada-pytorch](https://github.com/robgon-art/stylegan2-ada-pytorch)
